name: Build iOS .dylib for Swift Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Add UnmanagedExports package
      run: dotnet add package UnmanagedExports --version 1.2.6

    - name: Build and publish .dylib for iOS (arm64)
      run: |
        dotnet publish RSACryptoCSharpLibrary.csproj \
          -c Release \
          -f net9.0-ios \
          -r ios-arm64 \
          --self-contained true \
          -o bin/Release/net9.0-ios/ios-arm64/publish

    - name: Upload .dylib artifact
      uses: actions/upload-artifact@v3
      with:
        name: RSACryptoLibrary-dylib
        path: bin/Release/net9.0-ios/ios-arm64/publish
