name: Build iOS AOT Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios-aot:
    runs-on: macos-latest

    env:
      DOTNET_VERSION: '9.0.203'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install iOS workload
        run: dotnet workload install ios --skip-manifest-update

      - name: Restore dependencies
        run: dotnet restore

      - name: Build native AOT iOS dylib
        run: dotnet publish -c Release -f net9.0-ios -r ios-arm64 -p:PublishAot=true -p:PublishAotUsingRuntimePack=true

      - name: Upload iOS dylib artifact
        uses: actions/upload-artifact@main
        with:
          name: ios-native-lib
          path:  bin/Release/net9.0-ios/ios-arm64/publish/native/*.dylib 
