name: Build and Add UnmanagedExports Package

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for building .NET iOS projects

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0'  # Use .NET 9

    - name: Add UnmanagedExports package
      run: dotnet add package UnmanagedExports --version 1.2.6  # Add the UnmanagedExports package

    - name: Restore dependencies
      run: dotnet restore  # Restore the project dependencies

    - name: Build the project
      run: dotnet build --configuration Release  # Build the project in Release configuration

    - name: Publish the project for iOS
      run: dotnet publish --configuration Release --runtime ios-arm64 --self-contained false  # Publish for iOS ARM64

    - name: Zip the output
      run: |
        cd bin/Release/net9.0-ios/ios-arm64/publish
        zip -r output.zip .  # Create a zip file with the build output

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: RSACryptoLibrary
        path: bin/Release/net9.0-ios/ios-arm64/publish/output.zip  # Upload the .dylib artifact
